name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for posting your first issue. I'll try and respond to you asap.'
        pr-message: 'Hi! Thanks for getting involved with the project. It's good to have you on-board. I welcome any other improvements that you might have. Thanks.'
